spring:
  datasource:
    #url: jdbc:postgresql://127.0.0.1:5432/postgres                                      # default, proc fails
    #url: jdbc:postgresql://127.0.0.1:5432/postgres?escapeSyntaxCallMode=func            # same as default
    #url: jdbc:postgresql://127.0.0.1:5432/postgres?escapeSyntaxCallMode=call            # only proc calls work
    url: jdbc:postgresql://127.0.0.1:5432/postgres?escapeSyntaxCallMode=callIfNoReturn  # procs work, funcs don't but should?
    username: postgres
    password: password
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE